version: "2"
services:


  pwn:
    build:
      context: .
      dockerfile: Dockerfile  # Your Dockerfile
    #image: ctftraining/pwn_kafel_test  # This is for test, you can change this name
    volumes:
      - ./tcpdump:/var/lib/tcpdump # Tcp dump dir
    ports:
      - "10001:10000" # Must sync with pwn.xinetd.conf
    environment:
      - FLAG=ctftraining{base_pwn_xinetd_kafel_1804} # flag init 
      - TCPDUMP_ENABLE=1 
